name: Swift Lint

on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Run SwiftLint
        uses: docker://ghcr.io/realm/swiftlint@sha256:d4496a4b04b3f526f35100375f70d6d46ff4b700a6f28224f2fea815560b4aae
      - name: Run SwiftLint
        uses: docker://ghcr.io/realm/swiftlint@sha256:d4496a4b04b3f526f35100375f70d6d46ff4b700a6f28224f2fea815560b4aae
      - name: Run SwiftLint # 0.58.0
        uses: docker://ghcr.io/realm/swiftlint@sha256:d4496a4b04b3f526f35100375f70d6d46ff4b700a6f28224f2fea815560b4aae
