name: Swift Lint

on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Run SwiftLint
        uses: docker://ghcr.io/realm/swiftlint@sha256:b500fb49bbc7b752575cbb7124311686ce1055393b9e45cb63380ace67a58116 # 0.58.2
